# Generated by Django 4.0.5 on 2022-06-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
