# Generated by Django 4.0.5 on 2022-06-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_game_image_alter_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='loser',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
