# Generated by Django 4.0.5 on 2022-06-16 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0003_alter_matches_loser_alter_matches_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='competitor_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_one', to=settings.AUTH_USER_MODEL),
        ),
    ]
